/*+==========================================================================

File: MonitorServer.h

Summary:  Definition of CMonitorServer Class. Generated by VS6 ATL Wizard.

----------------------------------------------------------------------------

This file is part of the Microsoft COM+ Samples.

Copyright (C) 1995 - 2000 Microsoft Corporation. All rights reserved.

This source code is intended only as a supplement to Microsoft
Development Tools and/or on-line documentation. See these other
materials for detailed information regarding Microsoft code samples.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

==========================================================================+*/
// MonitorServer.h: Definition of the CMonitorServerClass class
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_MONITORSERVER_H__F159BD5F_4DA8_11D2_9672_00AA00B913AC__INCLUDED_)
#define AFX_MONITORSERVER_H__F159BD5F_4DA8_11D2_9672_00AA00B913AC__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#include <stdlib.h>
#include <time.h>
#include "resource.h"       // main symbols

/////////////////////////////////////////////////////////////////////////////
// CMonitorServerClass

class CMonitorServer :
	public IMonitorServer,
	public CComObjectRoot,
	public CComCoClass<CMonitorServer,&CLSID_MonitorServer>
{
public:
	CMonitorServer() { srand( (unsigned)time(NULL) );}
BEGIN_COM_MAP(CMonitorServer)
	COM_INTERFACE_ENTRY(IMonitorServer)
END_COM_MAP()
DECLARE_NOT_AGGREGATABLE(CMonitorServer)

DECLARE_REGISTRY_RESOURCEID(IDR_MonitorServer)

// IMonitorServer
    HRESULT STDMETHODCALLTYPE GetData(
	    /* [out] */ LONG __RPC_FAR *pData );
	
    HRESULT STDMETHODCALLTYPE GetPingResponder(
            /* [out] */ IPingResponder __RPC_FAR *__RPC_FAR *ppPing);

public:
};

#endif // !defined(AFX_MONITORSERVER_H__F159BD5F_4DA8_11D2_9672_00AA00B913AC__INCLUDED_)
