All:
!IFDEF NODEBUG
   nmake /f ByotTransaction.mak CFG="ByotTransaction - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f ByotTransaction.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF