<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>BYOT Sample - Commit/Abort Page</title>
</head>

<body bgcolor="#FFFFFF">

<form method="POST">
    <p align="center">Your transaction is now pending. Please
    choose one of the commands below.</p>
    <p align="center"><input type="submit" name="cmdCommit"
    value="Commit BYOT Transaction"><input type="submit"
    name="cmdAbort" value="Abort BYOT Transaction"></p>
</form>
</body>
</html>
