/*+==========================================================================

File: PingResponder.h

Summary:  Define implementation class (CPingResponder) for object that implements
          IPingResponder. Generated by VC6 ATL Wizard.

----------------------------------------------------------------------------

This file is part of the Microsoft COM+ Samples.

Copyright (C) 1995 - 2000 Microsoft Corporation. All rights reserved.

This source code is intended only as a supplement to Microsoft
Development Tools and/or on-line documentation. See these other
materials for detailed information regarding Microsoft code samples.

THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
PARTICULAR PURPOSE.

==========================================================================+*/
	
// PingResponder.h : Declaration of the CPingResponder

#ifndef __PINGRESP_H_
#define __PINGRESP_H_

#include "resource.h"       // main symbols

/////////////////////////////////////////////////////////////////////////////
// CPingResponder
class ATL_NO_VTABLE CPingResponder :
	public CComObjectRootEx<CComMultiThreadModel>,
	public CComCoClass<CPingResponder, &CLSID_PingResponder>,
	public IPingResponder
{
public:
	CPingResponder()
	{
	}

DECLARE_REGISTRY_RESOURCEID(IDR_PINGRESP)
DECLARE_NOT_AGGREGATABLE(CPingResponder)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CPingResponder)
	COM_INTERFACE_ENTRY(IPingResponder)
END_COM_MAP()

// IPingResponder
public:
	STDMETHOD(Ping)();
};

#endif //__PINGRESP_H_
