All:
!IFDEF NODEBUG
   nmake /f NewsEventClass.mak CFG="NewsEventClass - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f NewsEventClass.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF