#if !defined(AFX_AGENTCTLPROPERTYSHEET_H__AB8FEBA8_3841_11D2_8512_00C04FA34A14__INCLUDED_)
#define AFX_AGENTCTLPROPERTYSHEET_H__AB8FEBA8_3841_11D2_8512_00C04FA34A14__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CAgentCtlPropertySheet wrapper class

class CAgentCtlPropertySheet : public COleDispatchDriver
{
public:
	CAgentCtlPropertySheet() {}		// Calls COleDispatchDriver default constructor
	CAgentCtlPropertySheet(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAgentCtlPropertySheet(const CAgentCtlPropertySheet& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	short GetLeft();
	short GetTop();
	short GetHeight();
	short GetWidth();
	void SetVisible(BOOL bNewValue);
	BOOL GetVisible();
	void SetPage(LPCTSTR lpszNewValue);
	CString GetPage();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AGENTCTLPROPERTYSHEET_H__AB8FEBA8_3841_11D2_8512_00C04FA34A14__INCLUDED_)
