All:
!IFDEF NODEBUG
   nmake /f TxEnlister.mak CFG="TxEnlister - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f TxEnlister.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF