All:
!IFDEF NODEBUG
   nmake /f PersistATL.mak CFG="PersistATL - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f PersistATL.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF