All:
!IFDEF NODEBUG
   nmake /f CrmMonComp.mak CFG="CrmMonComp - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f CrmMonComp.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF