/****************************************************************************
                   Microsoft RPC Version 2.0
           Copyright Microsoft Corp. 1992 - 2000
                        repas Example

    FILE:       repassu.c

    PURPOSE:    Utility functions used by client side of the RPC
                distributed application.
                This sample demonstrates the represent_as attribute.

    RELATED:    repass.c - server main
                repasp.c - remote procedures
                repasc.c - client main

    FUNCTIONS:  CHAR_STRING_to_local    - convert CHAR_STRING to WCHAR_STRING
                CHAR_STRING_from_local  - convert CHAR_STRING from WCHAR_STRING
                CHAR_STRING_free_inst   - free CHAR_STRING memory
                CHAR_STRING_free_local  - free WCHAR_STRING memory
                midl_user_allocate - user-supplied memory allocator
                midl_user_free - user-supplied routine to free memory


    COMMENTS:   This sample program generates a client and server can share
                an interface, but one side can use a different representation
                than the other.

                The client side in this example does all operations using
                character strings, and the server side does all operations
                using UNICODE strings.  Two procedures are provided, one
                defined with ASCII strings, one with UNICODE strings.
                The wire format reflects these definitions, yet the client
                and server see pure ASCII and pure UNICODE respectively.

                The [represent_as] attribute (used in the client and server
                side acf files) requires the four user-supplied functions
                whose names start with the name of the transmitted type
                (in the server side's case: CHAR_STRING)

                The [in, out] attributes applied to remote procedure
                parameters require the two user-supplied functions
                midl_user_allocate and midl_user_free.

                The other functions are utilities that are used to
                build or display the data structures.

****************************************************************************/

#include <stdlib.h>
#include <stdio.h>
#include "repass.h"    // header file generated by MIDL compiler for client



/*
 Description:   Allocates memory for the transmitted type and converts from
                local type to the transmitted type
                
 Arguments:     
    pLocal:     pointer to local type
    ppWire:     pointer to the transmitted type pointer. This function should 
                allocate memory for the transmitted data type. 

 Return Value:  None.                    
*/
void __RPC_USER
CHAR_STRING_from_local(
    WCHAR_STRING __RPC_FAR * pLocal,
    CHAR_STRING __RPC_FAR * __RPC_FAR * ppWire )
{
    CHAR_STRING    *   pWireString;

    pWireString = midl_user_allocate( sizeof( CHAR_STRING ) );

    *ppWire = pWireString;

    wcstombs( *pWireString, *pLocal, STRING_SIZE );
}

/*
 Description:   Converts from transmitted type to local type.
                Memory for the local type has already been allocated by
                the stubs.
                
 Arguments:     
    pWire :     pointer to transmitted type
    pLocal:     pointer to local type

 Return Value:  None.                    
*/
void __RPC_USER
CHAR_STRING_to_local(
    CHAR_STRING __RPC_FAR * pWire,
    WCHAR_STRING __RPC_FAR * pLocal )
{
    mbstowcs( *pLocal, *pWire, STRING_SIZE );
}


/*
 Description:   Frees the memory allocated for the transmitted type.This
                includes the embedded pointers (if any).

 Arguments:     
    pWire:      pointer to the transmitted type

 Return Value:  None
 */
void __RPC_USER
CHAR_STRING_free_inst(
    CHAR_STRING __RPC_FAR * pWire)
{
    midl_user_free( pWire );
}


/*
 Descripton:    Frees embedded pointers in the local type(if any).
                Do not free the type itself

 Arguments:
    pLocal:     pointer to the local type

 Return Value:  None
 */
void __RPC_USER
CHAR_STRING_free_local(
    WCHAR_STRING __RPC_FAR * pLocal)
{
     /* As there are no embedded pointers in the
     * local type. So nothing to free
     */
     
     return; 
}

/***************************************************************************/

void __RPC_FAR * __RPC_USER midl_user_allocate(size_t len)
{
    return(malloc(len));
}

void __RPC_USER midl_user_free(void __RPC_FAR * ptr)
{
    free(ptr);
}


/***************************************************************************/

/* end file repassu.c */
