All:
!IFDEF NODEBUG
   nmake /f CrmFilesTest.mak CFG="CrmFilesTest - Win32 Release MinSize" -nologo /$(MAKEFLAGS) $(makeopts)
!ELSE
   nmake /f CrmFilesTest.mak -nologo /$(MAKEFLAGS) $(makeopts)
!ENDIF